name: Run Fractal Script

on:
  workflow_dispatch: # lets you trigger the script manually from the Actions tab

jobs:
  run-fractal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib

      - name: Run fractal script
        run: |
          python script.py/start.py
