name: Run Fractal Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run fractal script
        run: python script.py/start.py

      - name: Upload fractal output
        uses: actions/upload-artifact@v4
        with:
          name: fractal-video
          path: fractal_output.mp4
